#!/bin/bash
mkdir -p images
ruby png.rb white black red blue green yellow lightyellow gold purple orange brown tan beige cyan grey pink lightgreen darkgreen lightblue darkblue darkred lightgrey maroon teal navy olive
